# Generated by Django 5.1.7 on 2025-03-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug for a course.\n                            If not provided, default will be slugified title', unique=True),
        ),
    ]
