# Generated by Django 5.1.7 on 2025-03-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug for a course.\n                            If not provided, default will be slugified title'),
        ),
    ]
